### ISSUE TITLE
Registration Error 

### ISSUE THREAD

**Issue by HaseebUllahAbbasi** [ABIDULLAH786/Basic-Crud-APP-Using-EJS#1]
there is error in registration

**Comment by ABIDULLAH786** [comment]
Yah, thanks for your suggestion I have resolved it, i renovelled it by adding the bcrypt library in UserModal and refactored the code in if else to overcome the registration and already registered person issue

**Comment by HaseebUllahAbbasi** [comment]
Cheers 🥳
